resources:
  - name: distrolessGithubRepo
    type: GitRepo
    configuration:
      gitProvider: shahin_test
      path: shahiinn/jfrog-distroless
      branches:
        include: master
  - name: file_test
    type: FileSpec
    configuration:     
      sourceArtifactory: artifact_test
      pattern: testrepo1/distro-build.sh
      target: distro-build.sh
  - name: distrolessArtifactory
    type: BuildInfo
    configuration:
      sourceArtifactory: artifact_test
      buildName: docker_distro_build_pipe
      buildNumber: 1
pipelines:
  - name: DistrolessPipe
    steps:
      - name: start
        type: Bash
        configuration:
          affinityGroup: dockerGroup
          inputResources:
            - name: file_test
          outputResources:
            - name: distrolessGithubRepo
        execution:
          onExecute:
            - echo "Starting the build"
          onSuccess:
            - echo "Triggered the build"
      - name: docker_build_1
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: customize-example
          dockerFileName: Dockerfile.redhat-ubi-rt7
          dockerImageName: 'chartstesting-distroless-local.jfrog.io/artifactory-rh-ubi'
          dockerOptions: --build-arg ARTIFACTORY_BASE_VERSION=7.4.1
          dockerImageTag: ${run_number}
          inputResources:
            - name: distrolessGithubRepo
          integrations:
            - name: artifact_test
      - name: docker_build_2
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: customize-example
          dockerFileName: Dockerfile.python
          dockerImageName: 'chartstesting-distroless-local.jfrog.io/python'
          dockerImageTag: ${run_number}
          inputResources:
            - name: distrolessGithubRepo
          integrations:
            - name: artifact_test
      - name: docker_build_3
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: customize-example
          dockerFileName: Dockerfile.curl
          dockerImageName: 'chartstesting-distroless-local.jfrog.io/curl'
          dockerImageTag: ${run_number}
          inputResources:
            - name: distrolessGithubRepo
          integrations:
            - name: artifact_test
      - name: docker_build_4
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: customize-example
          dockerFileName: Dockerfile.distroless
          dockerImageName: 'chartstesting-distroless-local.jfrog.io/distroless'
          dockerImageTag: ${run_number}
          inputResources:
            - name: distrolessGithubRepo
          integrations:
            - name: artifact_test
      - name: docker_build_5
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: customize-example
          dockerFileName: Dockerfile.redhat-ubi
          dockerImageName: 'chartstesting-distroless-local.jfrog.io/redhat-ubi'
          dockerImageTag: ${run_number}
          inputResources:
            - name: distrolessGithubRepo
          integrations:
            - name: artifact_test            
      - name: docker_push_1
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: distroless-local
          integrations:
            - name: artifact_test
          inputSteps:
            - name: docker_build_1
      - name: docker_push_2
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: distroless-local
          integrations:
            - name: artifact_test
          inputSteps:
            - name: docker_build_2            
      - name: docker_push_3
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: distroless-local
          integrations:
            - name: artifact_test
          inputSteps:
            - name: docker_build_3            
      - name: docker_push_4
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: distroless-local
          integrations:
            - name: artifact_test
          inputSteps:
            - name: docker_build_4                        
      - name: docker_push_5
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: distroless-local
          integrations:
            - name: artifact_test
          inputSteps:
            - name: docker_build_5
          forceXrayScan: true
      - name: publish_build_info_1
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_1
          outputResources:
            - name: artifact_test           
      - name: publish_build_info_2
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_2
          outputResources:
            - name: artifact_test
      - name: publish_build_info_3
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_3
          outputResources:
            - name: artifact_test           
      - name: publish_build_info_4
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_4
          outputResources:
            - name: artifact_test           
      - name: publish_build_info_5
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_5
          outputResources:
            - name: artifact_test            
            
            
            
            
