resources:
  - name: distrolessGithubRepo
    type: GitRepo
    configuration:
      gitProvider: shahin_test
      path: shahiinn/jfrog-distroless
      branches:
        include: master
  - name: file_test
    type: FileSpec
    configuration:     
      sourceArtifactory: artifact_test
      pattern: testrepo1/distro-build.sh
      target: distro-build.sh
  - name: distrolessArtifactory
    type: BuildInfo
    configuration:
      sourceArtifactory: artifact_test
      buildName: DistrolessPipe
      buildNumber: 1
pipelines:
  - name: DistrolessPipe
    steps:
      - name: docker_build_1
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: customize-example
          dockerFileName: Dockerfile.redhat-ubi-rt7
          dockerImageName: 'chartstesting-distroless-local.jfrog.io/artifactory-rh-ubi'
          dockerOptions: --build-arg ARTIFACTORY_BASE_VERSION=7.4.1
          dockerImageTag: ${run_number}
          inputResources:
            - name: distrolessGithubRepo
          integrations:
            - name: artifact_test    
    
      - name: DockerPush
        type: Bash
        configuration:
          affinityGroup: dockerGroup
          inputResources:
            - name: file_test
          outputResources:
            - name: distrolessGithubRepo
        execution:
          onExecute:
            - echo "Starting the build"
            - curl -fL https://getcli.jfrog.io | sh
            - ./jfrog --version
            - export JFROG_CLI_OFFER_CONFIG=false; ./jfrog rt u docker-push chartstesting-distroless-local.jfrog.io/$res_docker_build_1_imageName distroless-local --build-name=DistrolessPipe --build-number=18 --server-id chartstesting --url ${int_artifact-test_url} --user ${int_artifact-test_user} --password ${int_artifact-test_apikey}
          onSuccess:
            - echo "Triggered the build"
