ARG ROUTER_BASE_VERSION=1.2.1
ARG UBI_BASE_IMAGE=ubi8

FROM docker.bintray.io/jfrog/router:${ROUTER_BASE_VERSION} AS base

# The new image based on registry.access.redhat.com/ubi
FROM registry.access.redhat.com/${UBI_BASE_IMAGE}

ARG ROUTER_BASE_VERSION
ARG UBI_BASE_IMAGE

LABEL name="JFrog Router" \
      description="JFrog Router image based on the Red Hat Universal Base Image." \
      vendor="JFrog" \
      summary="JFrog Router (Red Hat UBI)"

# Environment needed for Router
ENV JF_ROUTER_USER=router \
    ROUTER_USER_ID=1117 \
    ROUTER_VERSION=${ROUTER_BASE_VERSION} \
    JF_PRODUCT_HOME=/opt/jfrog/router \
    JF_PRODUCT_DATA_INTERNAL=/var/opt/jfrog/router \
    SERVICE_NAME=router

COPY --from=base /opt/jfrog/router /opt/jfrog/router

# Add license information to meet the Red Hat container image certification requirements
COPY --from=base /opt/jfrog/router/app/doc/* /licenses/

RUN mkdir -p /var/opt/jfrog && chmod 0777 /var/opt/jfrog

RUN useradd -M -s /usr/sbin/nologin --uid 1117 --user-group router && \
    chown -R 1117:1117 /opt/jfrog/router /var/opt/jfrog && \
    yum install -y --disableplugin=subscription-manager wget && \
    yum install -y --disableplugin=subscription-manager procps && \
    yum install -y --disableplugin=subscription-manager net-tools && \
    yum install -y --disableplugin=subscription-manager hostname

USER router

VOLUME /var/opt/jfrog/router

ENTRYPOINT ["/opt/jfrog/router/app/bin/entrypoint-router.sh"]
