ARG PIPELINES_BASE_VERSION

FROM docker.bintray.io/jfrog/pipelines-installer:${PIPELINES_BASE_VERSION} AS base

# The new image based on registry.access.redhat.com/ubi
FROM registry.access.redhat.com/ubi8

USER root

LABEL name="JFrog Pipelines Installer" \
      description="JFrog Pipelines Installer image based on the Red Hat Universal Base Image." \
      vendor="JFrog" \
      summary="JFrog Pipelines Installer (Red Hat UBI)" \
      com.jfrog.license_terms="https://jfrog.com/platform/enterprise-plus-eula/"

# Environment needed for Pipelines
ENV JF_PIPELINES_USER=pipelines \
    PIPELINES_USER_ID=1035 \
    PIPELINES_VERSION=${PIPELINES_BASE_VERSION} \
    JF_PRODUCT_HOME=/opt/jfrog/pipelines \
    JF_PRODUCT_DATA_INTERNAL=/var/opt/jfrog/pipelines

ENV NODE_PATH /usr/local/lib/node_modules
ENV TMP_DIR /opt/jfrog/pipelines/var/tmp
ENV SRC_DIR /opt/jfrog/pipelines/installer
ENV DEPENDENCIES /opt/jfrog/pipelines/dependencies

# COPY IN PIPELINES FROM BASE IMAGE
COPY --from=base /usr/local/lib /usr/local/lib
COPY --from=base /opt/jfrog/pipelines/var/tmp /opt/jfrog/pipelines/var/tmp
COPY --from=base /opt/jfrog/pipelines /opt/jfrog/pipelines

# Add EULA information to meet the Red Hat container image certification requirements
COPY entplus_EULA.txt /licenses/

RUN mkdir -p /var/opt/jfrog && chmod 0777 /var/opt/jfrog

RUN useradd -M -s /usr/sbin/nologin --uid 1035 --user-group pipelines && \
    chown -R 1035:1035 /opt/jfrog/pipelines /var/opt/jfrog && \
    yum install -y --disableplugin=subscription-manager wget && \
    yum install -y --disableplugin=subscription-manager procps && \
    yum install -y --disableplugin=subscription-manager net-tools && \
    yum install -y --disableplugin=subscription-manager hostname

USER ${JF_PIPELINES_USER}
WORKDIR /opt/jfrog/pipelines/installer
ENTRYPOINT ["/bin/bash", "execUtil.sh"]