ARG XRAY_BASE_VERSION=3.3.2
ARG UBI_BASE_IMAGE=ubi8

FROM docker.bintray.io/jfrog/xray-analysis:${XRAY_BASE_VERSION} AS base

# The new image based on registry.access.redhat.com/ubi
FROM registry.access.redhat.com/${UBI_BASE_IMAGE}

ARG XRAY_BASE_VERSION
ARG UBI_BASE_IMAGE

LABEL name="JFrog Xray Analysis" \
      description="JFrog Xray Analysis image based on the Red Hat Universal Base Image." \
      vendor="JFrog" \
      summary="JFrog Xray Analysis (Red Hat UBI)" \
      com.jfrog.license_terms="https://jfrog.com/xray/eula/"

# Environment needed for Xray
ENV JF_XRAY_USER=xray \
    XRAY_USER_ID=1035 \
    XRAY_VERSION=${XRAY_BASE_VERSION} \
    JF_PRODUCT_HOME=/opt/jfrog/xray \
    JF_PRODUCT_DATA_INTERNAL=/var/opt/jfrog/xray \
    SERVICE_NAME=analysis


COPY --from=base /opt/jfrog/xray /opt/jfrog/xray
COPY --from=base /postgresql-client /postgresql-client

# Add license information to meet the Red Hat container image certification requirements
COPY --from=base /opt/jfrog/xray/app/doc/* /licenses/

RUN mkdir -p /var/opt/jfrog && chmod 0777 /var/opt/jfrog

RUN useradd -M -s /usr/sbin/nologin --uid 1035 --user-group xray && \
    chown -R 1035:1035 /opt/jfrog/xray /var/opt/jfrog /postgresql-client && \
    yum install -y --disableplugin=subscription-manager wget && \
    yum install -y --disableplugin=subscription-manager procps && \
    yum install -y --disableplugin=subscription-manager net-tools && \
    yum install -y --disableplugin=subscription-manager hostname

USER xray

VOLUME /var/opt/jfrog/xray

ENTRYPOINT ["/opt/jfrog/xray/app/bin/wrapper.sh"]
